spring:
    application:
        name: To Do List
    datasource:
        url: jdbc:mysql://localhost:3306/todo_list
        username: root
        password: 1lcMNSTR0512!
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update